image: node:latest

stages:
  - test

cache:
  paths:
    - node_modules/
    - server/node_modules/

test:
  stage: test
  script:
    - npm install
    - npm install --prefix server
    - npm test
  only:
    - main
